DharanProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^configuration/', include('configuration.urls', namespace="configuration")),
    url('^course/', include('Course.urls', namespace='course')),
    url('^book/', include('books.urls', namespace='book')),
    url(r'^boards/', include('boards.urls', namespace='boards'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

books/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^books/$', views.book_list, name='book_list'),
    url(r'^books/create/$', views.book_create, name='book_create'),
]

books/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

books/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'publication_date', 'author', 'price', 'pages', 'book_type', )

books/views.py
# Create your views here.
from django.shortcuts import render
from .models import Book
from django.http import JsonResponse
from django.template.loader import render_to_string
from .forms import BookForm


def book_create(request):
    form = BookForm()
    context = {'form': form}
    html_form = render_to_string('books/includes/partial_book_create.html',
                                 context,
                                 request=request,
                                 )
    return JsonResponse({'html_form': html_form})


def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {'books': books})

templates/books/book_list.html
{% extends 'base.html' %}
{% load static %}

{% block javascript %}
    <script src="{% static 'js/book.js' %}"></script>
{% endblock %}

{% block body %}
    <h1 class="page-header">Books</h1>


    <p>
        <button type="button" class="btn btn-primary js-create-book">
            <span class="glyphicon glyphicon-plus"></span>
            New book
        </button>
    </p>
    <table class="table" id="book-table">
        <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Author</th>
            <th>Type</th>
            <th>Publication date</th>
            <th>Pages</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.get_book_type_display }}</td>
                <td>{{ book.publication_date }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="7" class="text-center bg-warning">No book</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <div class="modal fade" id="modal-book">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
{% endblock %}