DharanProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^configuration/', include('configuration.urls', namespace="configuration")),
    url('^course/', include('Course.urls', namespace='course')),
    url('^book/', include('books.urls', namespace='book')),
    url(r'^boards/', include('boards.urls', namespace='boards'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

boards/urls.py
from django.conf.urls import url

from boards import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    url(r'^(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),

]

books/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^books/$', views.book_list, name='book_list'),
    url(r'^books/create/$', views.book_create, name='book_create'),
]

boards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def get_post_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

    def __str__(self):
        return self.name


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics')
    starter = models.ForeignKey(User, related_name='topics')
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts')
    updated_by = models.ForeignKey(User, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

boards/forms.py
from django import forms
from .models import Topic,Post


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(), max_length=4000,
                              help_text='The max length of the text is 4000.')

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

boards/views.py
from django.shortcuts import render, redirect, reverse

from django.http import HttpResponse
from .models import Board, Topic, Post
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .forms import NewTopicForm, PostForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count


@login_required
def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            return redirect('boards:topic_posts', pk=pk, topic_pk=topic_pk)
    else:
        form = PostForm()
    return render(request, 'boards/reply_topic.html', {'topic': topic, 'form': form})


def topic_posts(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    topic.views += 1
    topic.save()
    return render(request, 'boards/topic_posts.html', {'topic': topic})


def home(request):
    boards = Board.objects.all()

    return render(request, 'boards/board_list.html', {'boards': boards})


def board_topics(request, pk):
    board = get_object_or_404(Board, pk=pk)
    topics = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
    return render(request, 'boards/board_topics.html', {'board': board, 'topics': topics})


@login_required
def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    user = request.user
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()
            post = Post.objects.create(message=form.cleaned_data.get('message'),
                                       topic=topic, created_by=user)

            return redirect('boards:board_topics', pk=pk, topic__pk=topic.pk)
    else:
        form = NewTopicForm()

    return render(request, 'boards/new_topic.html', {'board': board, 'form': form})

templates/boards/board_list.html
{% extends 'base.html' %}
{% block body %}
    <br>
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item active">Boards</li>
        </ol>
        <table class="table">
            <thead class="" style="background-color: black;color: white;">
            <tr>
                <th>Board</th>
                <th>Posts</th>
                <th>Topics</th>
                <th>Last Post</th>
            </tr>
            </thead>
            <tbody>
            {% for board in boards %}
                <tr>
                    <td>
                        <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
                        <small class="text-muted d-block">{{ board.description }}</small>
                    </td>
                    <td class="-align-center">{{ board.get_post_count }}</td>
                    <td class="-align-center">{{ board.topics.count }}</td>
                    <td class="-align-center">
                        {% with post=board.get_last_post %}
                            {% if post %}
                                <small>
                                    <a href="{% url 'boards:topic_posts' board.pk post.topic.pk %}">
                                        By {{ post.created_by.username }} at {{ post.created_at }}
                                    </a>
                                </small>
                            {% else %}
                                <small class="text-muted">
                                    <em>No posts yet.</em>
                                </small>
                            {% endif %}
                        {% endwith %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/boards/board_topics.html
{% extends 'base.html' %}
{% block body %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb my-4">
                    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
                    <li class="breadcrumb-item active">{{ board.name }}</li>
                </ol>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">New topic</a>
            </div>
        </div>

        <br>
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead class="" style="color:white;background-color: black;">
                    <tr>
                        <th>Topic</th>
                        <th>Starter</th>
                        <th>Replies</th>
                        <th>Views</th>
                        <th>Last Update</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for topic in topics %}
                        <tr>
                            <td><a href="{% url 'boards:topic_posts' board.pk topic.pk %}">
                                {{ topic.subject }}</a></td>
                            <td>
                                {{ topic.starter.username }}
                            </td>
                            <td>{{ topic.replies }}</td>
                            <td>{{ topic.views }}</td>
                            <td>{{ topic.last_updated }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>
{% endblock %}

templates/boards/new_topic.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
            <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>
            <li class="breadcrumb-item active">New topic</li>
        </ol>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}

                            {% if form.is_bound %}
                                {% if field.errors %}

                                    {% render_field field class="form-control is-invalid" %}
                                    {% for error in field.errors %}
                                        <div class="invalid-feedback">
                                            {{ error }}
                                        </div>
                                    {% endfor %}

                                {% else %}
                                    {% render_field field class="form-control is-valid" %}
                                {% endif %}
                            {% else %}
                                {% render_field field class="form-control" %}
                            {% endif %}

                            {% if field.help_text %}
                                <small class="form-text text-muted">
                                    {{ field.help_text }}
                                </small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success">Post</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/boards/register.html
{% extends 'base.html' %}
{% block body %}

    <div class="container-fluid">
        <h1 class="text-center logo my-4">
            <a href="{% url 'boards:home' %}">Django Boards</a>
        </h1>
        <div class="row justify-content-center">
            <div class="col-lg-4"></div>
            <div class="col-lg-4 col-md-10 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Sign up</h3>
                        <form method="post" novalidate>
                            {% csrf_token %}
                            {% include 'boards/includes/forms.html' %}
                            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
                        </form>
                    </div>
                    <div class="card-footer text-muted text-center">
                        Already have an account? <a href="#">Log in</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4"></div>
        </div>
    </div>
{% endblock %}

templates/boards/reply_topic.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <form method="post" class="mb-4">
        {% csrf_token %}
        {% include 'boards/includes/forms.html' %}
        <button type="submit" class="btn btn-success">Post a reply</button>
    </form>

    {% for post in topic.posts.all %}
        <div class="card mb-2">
            <div class="card-body p-3">
                <div class="row mb-3">
                    <div class="col-6">
                        <strong class="text-muted">{{ post.created_by.username }}</strong>
                    </div>
                    <div class="col-6 text-right">
                        <small class="text-muted">{{ post.created_at }}</small>
                    </div>
                </div>
                {{ post.message }}
            </div>
        </div>
    {% endfor %}

</div>
{% endblock %}

templates/boards/topic_posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ topic.subject }}{% endblock %}
{% block body %}
    <br>

    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
            <li class="breadcrumb-item"><a
                    href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
            <li class="breadcrumb-item active">{{ topic.subject }}</li>
        </ol>
    </div>

    <div class="container">

        <div class="mb-4">
            <a href="#" class="btn btn-primary" role="button">Reply</a>
        </div>

        {% for post in topic.posts.all %}
            <div class="card mb-2{% if forloop.first %}border-dark{% endif %}">
                {% if forloop.first %}
                    <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
                {% endif %}
                <div class="card-body p-3">
                    <div class="row">
                        <div class="col-2">
                            <img src="" alt="{{ post.created_by.username }}"
                                 class="w-100">
                            <small>Posts: {{ post.created_by.posts.count }}</small>
                        </div>
                        <div class="col-md-4">
                            <div class="row mb-3">
                                <div class="col-md-2">
                                    <strong class="text-muted">{{ post.created_by.username }}</strong>
                                </div>
                                <div class="col-6 text-right">
                                    <small class="text-muted">{{ post.created_at }}</small>
                                </div>
                            </div>
                            {{ post.message }}
                            {% if post.created_by == user %}
                                <div class="mt-3">
                                    <a href="#" class="btn btn-primary btn-sm" role="button">Edit</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <hr>
        {% endfor %}
{% endblock %}