Course/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Course import views

urlpatterns = [
    url(r'^$', views.course_home, name='course'),

    url(r'^course/new/$', views.course_new, name='course_new'),
    url(r'^courses/$', views.course_list, name='course_list'),
    url(r'^course/(?P<pk>\d+)/edit/$', views.course_edit, name='course_edit'),
    url(r'^course/(?P<pk>\d+)/delete/$', views.course_delete, name='course_delete'),
    url(r'^courses/create/$', views.course_create, name='course_create'),

]

DharanProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^configuration/', include('configuration.urls', namespace="configuration")),
    url('^course/', include('Course.urls', namespace='course')),
    url('^book/', include('books.urls', namespace='book')),
    url(r'^boards/', include('boards.urls', namespace='boards'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

books/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^books/$', views.book_list, name='book_list'),
    url(r'^books/create/$', views.book_create, name='book_create'),
]

Course/models.py
from django.db import models
from django.utils import timezone


class Course(models.Model):
    name = models.CharField(max_length=120, unique=True)
    code = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name

Course/forms.py
from django import forms
from .models import Course


class CourseForm(forms.ModelForm):
    # name = forms.CharField(
    #     label='Course Name ',
    #     widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the name of course'})
    # )
    #
    # code = forms.CharField(
    #     label='Course Code',
    #     widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the code of course'})
    #
    # )

    class Meta:
        model = Course
        fields = ('name', 'code',)

Course/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from .forms import CourseForm
from django.utils import timezone
from .models import Course
from django.contrib import messages
from .forms import CourseForm
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.db.models import ProtectedError


def course_create(request):
    data = dict()
    if request.method == "POST":
        form = CourseForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            courses = Course.objects.all()
            data['html_course_list'] = render_to_string('course/includes/partial_course_list.html',
                                                        {'courses': courses
                                                         })
        else:
            data['form_is_valid'] = False

    else:
        form = CourseForm()
    context = {
        'form': form
    }
    data['html_form'] = render_to_string('course/includes/partial_course_create.html',
                                         context, request=request)
    return JsonResponse


# Create your views here.
def course_home(request):
    return render(request, 'configuration/configuration_home.html')


def course_new(request):
    if request.method == "POST":
        course_form = CourseForm(request.POST or None, request.FILES or None)  # it request form from form.py
        if course_form.is_valid():
            course = course_form.save(commit=False)
            course.author = request.user
            course.published_date = timezone.now()
            course.save()
            return redirect('/')
    else:
        course_form = CourseForm()
    return render(request, 'course/courses.html', {'course_form': course_form})


def course_list(request):
    if request.user.is_staff:
        courses = Course.objects.all().order_by('name')
        context = {
            'courses': courses,

        }
        return render(request, 'course/courses.html', context)
    else:
        messages.error(request, 'Not enough Previliges ')
        return redirect('accounts:dashboard')


def course_edit(request, pk):
    if request.user.is_staff:
        course = get_object_or_404(Course, id=pk)
        if request.method == 'POST':
            course_form = CourseForm(request.POST, request.FILES or None, instance=course)
            if course_form.is_valid():
                course = course_form.save(commit=False)
                course.author = request.user
                course.save()
                return redirect('course:course_list')

        else:
            course_form = CourseForm(instance=Course)

        return render(request, 'course/courses.html', {'course_form': course_form}, )


def course_delete(request, pk):
    if request.user.is_staff:
        try:
            course = get_object_or_404(Course, id=pk)
            course.delete()
            messages.error(request, 'Course has been deleted . ')
        except ProtectedError:
            messages.warning(request, "Error Deleting Delete first associated batch")

        return redirect('course:course_list')

templates/course/includes/partial_course_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'course:course_create' %}" class="js-course-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Create a new course</h4>
    </div>
    <div class="modal-body">
        {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                    <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create course</button>
    </div>
</form>

templates/course/includes/partial_course_list.html
{% for course in courses %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ course.name }}</td>
        <td>{{ course.code }}</td>
        <td>
            <a href="{% url 'course:course_edit' pk=course.id %}">
                <button class="btn btn-primary btn-sm" data-toggle="modal"
                        data-target="#myModal"><i class="fa fa-edit"></i> Edit
                </button>
            </a>
            <button data-toggle="modal" data-target="#course-{{ course.id }}"
                    class="btn btn-danger btn-sm"><i
                    class="fa fa-trash"></i>Delete
            </button>
        </td>

    </tr>
{% empty %}
    <tr>
        <td colspan="7" class="text-center bg-warning">No Course</td>
    </tr>
{% endfor %}