Course/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Course import views

urlpatterns = [
    url(r'^$', views.course_home, name='course'),

    url(r'^course/new/$', views.course_new, name='course_new'),
    url(r'^courses/$', views.course_list, name='course_list'),
    url(r'^course/(?P<pk>\d+)/edit/$', views.course_edit, name='course_edit'),
    url(r'^course/(?P<pk>\d+)/delete/$', views.course_delete, name='course_delete'),
    url(r'^courses/create/$', views.course_create, name='course_create'),

]

DharanProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls', namespace="accounts")),
    url(r'^configuration/', include('configuration.urls', namespace="configuration")),
    url('^course/', include('Course.urls', namespace='course')),
    url('^book/', include('books.urls', namespace='book')),
    url(r'^boards/', include('boards.urls', namespace='boards'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

books/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^books/$', views.book_list, name='book_list'),
    url(r'^books/create/$', views.book_create, name='book_create'),
]

configuration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from configuration import views

urlpatterns = [
    url(r'', views.configuration, name='configuration'),
]

configuration/models.py
from django.db import models

# Create your models here.

configuration/views.py
from django.shortcuts import render


# Create your views here.
def configuration(request):
    return render(request, 'configuration/configuration.html')

templates/configuration/configuration.html
{% extends 'base.html' %}
{% block title %}configuration{% endblock %}
{% block script %}



{% endblock %}
{% block body %}

    <main class="main-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h4>configuration |
                        <small>Home</small>
                    </h4>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="/">Home</a></li>
                        <li class="active">configuration</li>
                    </ol>
                </div>
            </div>


            <div class="row">
                <div class="col-md-3 text-center">
                    <a href="{% url 'course:course' %}" data-toggle="tooltip"
                       title="Add a new course or batch or section for this academic year ">

                        <div class="page-div-wrapper bk-clr-page-one">
                            <i class="fa fa-book page-div-icon"></i>
                            <h4 class="list-group-item-heading">Manage Course/Batch/Section</h4>
                        </div>
                    </a>

                </div>
                <div class="col-md-3 text-center">

                </div>
                <div class="col-md-3 text-center">

                </div>
                <div class="col-md-3 text-center">

                </div>
            </div>
        </div>

    </main>
{% endblock %}

templates/configuration/configuration_home.html
{% extends 'base.html' %}
{% block title %}Configurations {% endblock %}
{% block body %}

    <main class="main-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h4>configuration |
                        <small>Home</small>
                    </h4>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="/">Home</a></li>
                        <li><a href="{% url 'configuration:configuration' %}">configuration</a></li>
                        <li class="active">courses</li>
                    </ol>
                </div>
            </div>


            <div class="row">
                <div class="col-md-4 text-center">
                    <a href="{% url 'course:course_list' %}" data-toggle="tooltip"
                       title="Add / Update /Delete Courses">

                        <div class="page-div-wrapper bk-clr-page-one">
                            <i class="fa fa-cog page-div-icon"></i>
                            <h4 class="list-group-item-heading">Manage Course</h4>
                        </div>
                    </a>

                </div>
                <div class="col-md-4 text-center">
                    <a href="{% url 'course:course' %}" data-toggle="tooltip"
                       title="Add / Update /Delete Batches">

                        <div class="page-div-wrapper bk-clr-page-one">
                            <i class="fa fa-cog page-div-icon"></i>
                            <h4 class="list-group-item-heading">Manage Batch</h4>
                        </div>
                    </a>

                </div>
                <div class="col-md-4 text-center">
                    <a href="{% url 'course:course' %}" data-toggle="tooltip"
                       title="Add / Update /Delete Sections">

                        <div class="page-div-wrapper bk-clr-page-one">
                            <i class="fa fa-cog page-div-icon"></i>
                            <h4 class="list-group-item-heading">Manage Section</h4>
                        </div>
                    </a>

                </div>

            </div>
        </div>

    </main>
{% endblock %}